version: "3"

services:
  localhost:
    build: .
    ports:
      - 80:80
      - 443:443
    links:
      - adminer
      - metabase

  adminer:
    image: adminer

  metabase:
    image: metabase/metabase
    ports:
      - 3000:3000
